version: "3.2"
services:

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./docker-config/site.conf:/etc/nginx/conf.d/site.conf
  #     - ./log/nginx:/var/log/nginx

  mongo:
    image: mongo
    volumes:
      - ./db/mongo:/data/db
    # ports:
    #   - "27017:27017"

  redis:
    image: redis
    volumes:
      - ./db/redis:/data

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file: .env
    command: ["npm", "run", "dev"]